### PR TITLE
New ObjectGraph data from QQ 7.2-8.1 on Android

### PR DESCRIPTION
**Pull request by foolip**
The APKs were found as described in
https://github.com/GoogleChromeLabs/confluence/pull/248.

The filenames were:
qqbrowser_7.2.1.2965_20820.apk
qqbrowser_7.3.1.3060_20820.apk
qqbrowser_7.5.1.3270_20820.apk
qqbrowser_7.6.1.3350_20820.apk
qqbrowser_7.8.0.3540_20820.apk
qqbrowser_8.0.0.3720_20820.apk
qqbrowser_8.1.3.3850_20820.apk

Script used:
```
for apk in qqbrowser_*.apk; do
  read -p "Press enter to install and launch $apk"
  adb install -r "$apk"
  adb shell am start -a android.intent.action.VIEW -d https://wpt.foolip.org com.tencent.mtt
done
```

Note that the package names are x.y.z, but only x.y appear in the
UA string and in the filenames added here.

### CODE REVIEW

**Comment by foolip** [comment]
@mdittmer, I believe that if you merge this and https://github.com/GoogleChromeLabs/confluence/pull/248 things will still blow up because of the differences in version numbers.

https://webkit.org/blog/8042/release-notes-for-safari-technology-preview-46/ ("Froze the user-agent string to reduce web compatibility risk and to prevent its use for fingerprinting") will present a similar problem, where we won't be able to get the product version from anything web exposed.

Here, should I just rename the files to add the missing digit, or will that break something anyway?

**Comment by foolip** [comment]
Of interest in this data is that QQ had "Chrome/37.0.0.0" in the UA string until 8.0, and in 8.1 it became "Chrome/57.0.2987.132".

**Comment by mdittmer** [comment]
https://webkit.org/blog/8042/release-notes-for-safari-technology-preview-46/ ("Froze the user-agent string to reduce web compatibility risk and to prevent its use for fingerprinting")

Fffffffffffffuuuuuuuuuuuuu

**Comment by mdittmer** [comment]
... maybe we should add input controls for the UA-sniffed info. That way the user can modify it before posting data.

**Comment by mdittmer** [comment]
You're right. Stuff will break. Can you rename the files before we merge this?

**Comment by foolip** [comment]
Happy to rename the files if the filename is what matters (as opposed to the UA string within).

**Comment by foolip** [comment]
I pushed a rename commit. Probably best to merge as two commits so that the original filenames are in the history.

**Pull request merged**
