### PR TITLE
Add OG data from UC Browser 11.8.2 (Chinese)

### PR DESCRIPTION
**Pull request by foolip**
APK downloaded from http://wap.uc.cn/verlist/chinese_999/ucbrowser/145

Filename was UCBrowser_V11.8.2.962_android_pf145_(Build171225134847).apk

The data was collected on a secure origin (HTTPS).

### CODE REVIEW

**Comment by mdittmer** [comment]
https://github.com/mdittmer/object-graph-js/blob/master/src/NameRewriter.js uses an ordered list of browser+platform "matchers" to interpret UA strings. It is leveraged by `ObjectGraph.js` in the same directory.

**Comment by foolip** [comment]
OK, let's do https://github.com/mdittmer/object-graph-js/pull/19 first. I've tried running with that locally, but by copying the file into place and not changing "git://github.com/mdittmer/object-graph-js.git" and it didn't work. So it's possible my PR isn't correct.

**Comment by foolip** [comment]
Closing this in favor of https://github.com/mdittmer/web-apis/pull/47, although I didn't get to 11.8.2 there.

**Comment by mdittmer** [comment]
Np. Feel free to open more PRs with new data as you're able to gather it.

**Pull request closed without merging**
