### PR TITLE
Collect data from Chrome 74

### PR DESCRIPTION
**Pull request by foolip**
Collected manually on a Windows machine as BrowserStack doesn't have
it yet, the Chrome 74 it has is beta channel.

### CODE REVIEW

**Comment by foolip** [comment]
Note that the Windows machine was on Insider Preview so there is some small chance that there will be differences to Chrome 73 caused by this. I think it's not likely, but will have to check that before actually deploying Confluence based on this data.

**Comment by Hexcles** [comment]
I've merged it for now. We can revert it if the data looks funny.

**Comment by foolip** [comment]
Yep, thanks!

**Comment by foolip** [comment]
Now deployed to https://web-confluence.appspot.com/#!/ and it looks fine, no additions or removals compared to Chrome 73 that seem suspect.

**Comment by foolip** [comment]
In light of https://github.com/mdittmer/web-apis/pull/91 this was a bit suspect, but I tried recollecting using BrowserStack and found that the only thing that changed was the timestamp and the version, from 74.0.3729.108 to 74.0.3729.131. Thus no important differences in the object graph data collected.

**Pull request merged**
